[package]
name = "RocketRust"
version = "0.1.0"
authors = ["Rocketman <759094438@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.41.0"
gl = "0.14.0"
gl_loader = "0.1.2"
