[package]
name = "RocketRust"
version = "0.1.0"
authors = ["Rocketman <759094438@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
